- README.md
Add papers about input context compression that accelerate LLMs inference.
Add new papers about KV Compression.
> add context compression & new papers KV compression

- README.md
> Add Microbenchmark

- README.md
update [Decoding Speculative Decoding]
[code](https://github.com/uw-mad-dash/decoding-speculative-decoding)
> update [Decoding Speculative Decoding] github repo

- README.md
Hi, I would like to introduce our recent survey paper! Hope you can merge this pull request if you find it useful!
Improving the reasoning ability of large language models (LLMs) and mitigating the hallucination problem are crucial research topics. After extensive thought, we realized that these two issues, "enhancing reasoning" and "alleviating hallucinations," share the same fundamental nature. We approached these issues from the perspective of internal consistency. This perspective allowed us to unify many seemingly unrelated works into a single framework. To improve internal consistency (which in turn enhances reasoning ability and mitigates hallucinations), we identified common elements across various works and summarized them into a Self-Feedback framework.
This framework consists …
> Add paper "Internal Consistency and Self-Feedback in Large Language Models: A Survey"

- README.md
> 🔥[flashinfer] FlashInfer: Kernel Library for LLM Serving(@flashinfer-ai)

- README.md
Lookup Table Enables Efficient Low-Bit LLM Inference Acceleration
> 🔥🔥[LUT TENSOR CORE] Lookup Table Enables Efficient Low-Bit LLM Inference Acceleration

- README.md
🔥🔥[Eigen Attention] Attention in Low-Rank Space for KV Cache Compression
> 🔥🔥[Eigen Attention] Attention in Low-Rank Space for KV Cache Compression

- README.md
KOALA: Enhancing Speculative Decoding for LLM via Multi-Layer Draft Heads with Adversarial Learning
> KOALA: Enhancing Speculative Decoding for LLM via Multi-Layer Draft Heads with Adversarial Learning

- README.md
Kraken: Inherently Parallel Transformers For Efficient Multi-Device Inference
> Kraken: Inherently Parallel Transformers For Efficient Multi-Device Inference

- README.md
> 🔥[ABQ-LLM] Arbitrary-Bit Quantized Inference Acceleration for Large Language Models

- README.md
- 🔥[Speculative Decoding] Parallel Speculative Decoding with Adaptive Draft Length
> 🔥[Speculative Decoding] Parallel Speculative Decoding with Adaptive Draft Length

- README.md
🔥🔥[MARLIN] MARLIN: Mixed-Precision Auto-Regressive Parallel Inference on Large Language Models
> 🔥🔥[MARLIN] MARLIN: Mixed-Precision Auto-Regressive Parallel Inference on Large Language Models

- README.md
🔥[ACTIVATION SPARSITY] TRAINING-FREE ACTIVATION SPARSITY IN LARGE LANGUAGE MODELS
> 🔥[ACTIVATION SPARSITY] TRAINING-FREE ACTIVATION SPARSITY IN LARGE LANGUAGE MODELS

- README.md
🔥[Decentralized LLM] Decentralized LLM Inference over Edge Networks with Energy Harvesting
> 🔥[Decentralized LLM] Decentralized LLM Inference over Edge Networks with Energy Harvesting

- README.md
…ature Sampling and Partial Alignment Distillation
> 🔥[Speculative Decoding] Boosting Lossless Speculative Decoding via Feature Sampling and Partial Alignment Distillation

- README.md
… Encoding for Fast and Improved LLM Inference
> 🔥🔥[Prompt Compression] Prompt Compression with Context-Aware Sentence Encoding for Fast and Improved LLM Inference

- README.md
🔥[CHESS] CHESS : Optimizing LLM Inference via Channel-Wise Thresholding and Selective Sparsification
> 🔥[CHESS] CHESS : Optimizing LLM Inference via Channel-Wise Thresholding and Selective Sparsification

- README.md
🔥[SpMM] High Performance Unstructured SpMM Computation Using Tensor Cores
> 🔥[SpMM] High Performance Unstructured SpMM Computation Using Tensor Cores

- README.md
🔥[RetrievalAttention] Accelerating Long-Context LLM Inference via Vector Retrieval
> 🔥[RetrievalAttention] Accelerating Long-Context LLM Inference via Vector Retrieval

- README.md
🔥[Inf-MLLM] Inf-MLLM: Efficient Streaming Inference of Multimodal Large Language Models on a Single GPU
> 🔥[Inf-MLLM] Inf-MLLM: Efficient Streaming Inference of Multimodal Large Language Models on a Single GPU

- README.md
🔥[InstInfer] InstInfer: In-Storage Attention Offloading for Cost-Effective Long-Context LLM Inference
> 🔥[InstInfer] InstInfer: In-Storage Attention Offloading for Cost-Effective Long-Context LLM Inference

- README.md
🔥🔥[CRITIPREFILL] CRITIPREFILL: A SEGMENT-WISE CRITICALITYBASED APPROACH FOR PREFILLING ACCELERATION IN LLMS
> 🔥🔥[CRITIPREFILL] CRITIPREFILL: A SEGMENT-WISE CRITICALITYBASED APPROACH FOR PREFILLING ACCELERATION IN LLMS

- README.md
> 🔥[VPTQ] VPTQ: EXTREME LOW-BIT VECTOR POST-TRAINING QUANTIZATION FOR LARGE LANGUAGE MODELS

- README.md
🔥🔥[INT-FLASHATTENTION] INT-FLASHATTENTION: ENABLING FLASH ATTENTION FOR INT8 QUANTIZATION
> 🔥🔥[INT-FLASHATTENTION] INT-FLASHATTENTION: ENABLING FLASH ATTENTION FOR INT8 QUANTIZATION

- README.md
[Low-bit] A Survey of Low-bit Large Language Models: Basics, Systems, and Algorithms
> [Low-bit] A Survey of Low-bit Large Language Models: Basics, Systems, and Algorithms

- README.md
🔥[AlignedKV] AlignedKV: Reducing Memory Access of KV-Cache with Precision-Aligned Quantization
> 🔥[AlignedKV] AlignedKV: Reducing Memory Access of KV-Cache with Precision-Aligned Quantization

- README.md
🔥🔥[Tensor Cores] Efficient Arbitrary Precision Acceleration for Large Language Models on GPU Tensor Cores
> 🔥🔥[Tensor Cores] Efficient Arbitrary Precision Acceleration for Large Language Models on GPU Tensor Cores

- README.md
🔥[KV-COMPRESS] PAGED KV-CACHE COMPRESSION WITH VARIABLE COMPRESSION RATES PER ATTENTION HEAD
> 🔥[KV-COMPRESS] PAGED KV-CACHE COMPRESSION WITH VARIABLE COMPRESSION RATES PER ATTENTION HEAD

- README.md
🔥[**LayerKV**] Optimizing Large Language Model Serving with Layer-wise KV Cache Management
> 🔥[LayerKV] Optimizing Large Language Model Serving with Layer-wise KV Cache Management

- README.md
🔥[LORC] Low-Rank Compression for LLMs KV Cache with a Progressive Compression Strategy
> 🔥[LORC] Low-Rank Compression for LLMs KV Cache with a Progressive Compression Strategy

- README.md
Large Language Model Performance Benchmarking on Mobile Platforms: A Thorough Evaluation
> Large Language Model Performance Benchmarking on Mobile Platforms: A Thorough Evaluation

- README.md
[LLM Inference] LARGE LANGUAGE MODEL INFERENCE ACCELERATION: A COMPREHENSIVE HARDWARE PERSPECTIVE
> [LLM Inference] LARGE LANGUAGE MODEL INFERENCE ACCELERATION: A COMPREHENSIVE HARDWARE PERSPECTIVE

- README.md
🔥[PARALLELSPEC] PARALLELSPEC: PARALLEL DRAFTER FOR EFFICIENT SPECULATIVE DECODING
> 🔥[PARALLELSPEC] PARALLELSPEC: PARALLEL DRAFTER FOR EFFICIENT SPECULATIVE DECODING

- README.md
This paper presents a novel hybrid inference approach that leverages the strengths of SLMs and LLMs while minimizing reliance on costly cloud-based LLMs. Unlike existing methods that route entire queries to either an SLM or a cloud LLM, this approach introduces a reward-based mechanism to dynamically determine the involvement of the cloud LLM during token generation. Specifically, each token predicted by the SLM is evaluated against a reward score, and only when this score falls below a certain threshold is the cloud LLM consulted for assistance in the next token prediction. This method not only reduces the traffic to the cloud LLM, thereby lowering costs, but also allows for flexible control over response quality depending on the reward score threshold. Experimental results demonstrate …
> Efficient Hybrid Inference for LLMs: Reward-Based Token Modelling with Selective Cloud Assistance

- README.md
🔥[FastAttention] FastAttention: Extend FlashAttention2 to NPUs and Low-resource GPUs for Efficient Inference
> 🔥[FastAttention] FastAttention: Extend FlashAttention2 to NPUs and Low-resource GPUs for Efficient Inference

- README.md
🔥[Tensor Product] Acceleration of Tensor-Product Operations with Tensor Cores
> 🔥[Tensor Product] Acceleration of Tensor-Product Operations with Tensor Cores

- README.md
🔥🔥[SP: BPT] Blockwise Parallel Transformer for Large Context Models
> 🔥🔥[SP: BPT] Blockwise Parallel Transformer for Large Context Models

- README.md
🔥🔥[TP: Comm Compression] Communication Compression for Tensor Parallel LLM Inference
> 🔥🔥[TP: Comm Compression] Communication Compression for Tensor Parallel LLM Inference

- README.md
🔥[SageAttention] SAGEATTENTION: ACCURATE 8-BIT ATTENTION FOR PLUG-AND-PLAY INFERENCE ACCELERATION(@thu-ml)
> 🔥[SageAttention] SAGEATTENTION: ACCURATE 8-BIT ATTENTION FOR PLUG-AND-PLAY INFERENCE ACCELERATION(@thu-ml)

- README.md
🔥[SageAttention-2] SageAttention2 Technical Report: Accurate 4 Bit Attention for Plug-and-play Inference Acceleration(@thu-ml)
> 🔥[SageAttention-2] SageAttention2 Technical Report: Accurate 4 Bit Attention for Plug-and-play Inference Acceleration(@thu-ml)

- README.md
🔥[Squeezed Attention] SQUEEZED ATTENTION: Accelerating Long Context Length LLM Inference(@UC Berkeley)
> 🔥[Squeezed Attention] SQUEEZED ATTENTION: Accelerating Long Context Length LLM Inference(@UC Berkeley)

- README.md
🔥[SparseInfer] SparseInfer: Training-free Prediction of Activation Sparsity for Fast LLM Inference
> 🔥[SparseInfer] SparseInfer: Training-free Prediction of Activation Sparsity for Fast LLM Inference

- README.md
🔥[Star-Attention: 11x~ speedup] Star Attention: Efficient LLM Inference over Long Sequences
> 🔥[Star-Attention: 11x~ speedup] Star Attention: Efficient LLM Inference over Long Sequences

- README.md
…or Recallable Compression
🔥[ClusterKV] ClusterKV: Manipulating LLM KV Cache in Semantic Space for Recallable Compression
> 🔥[ClusterKV] ClusterKV: Manipulating LLM KV Cache in Semantic Space for Recallable Compression

- README.md
…bal Prefix Sharing and Throughput-oriented Token Batching
🔥[BatchLLM] BatchLLM: Optimizing Large Batched LLM Inference with Global Prefix Sharing and Throughput-oriented Token Batching
> 🔥[BatchLLM] BatchLLM: Optimizing Large Batched LLM Inference with Global Prefix Sharing and Throughput-oriented Token Batching

- README.md
🔥🔥[TurboAttention] TURBOATTENTION: EFFICIENT ATTENTION APPROXIMATION FOR HIGH THROUGHPUTS LLMS
> 🔥🔥[TurboAttention] TURBOATTENTION: EFFICIENT ATTENTION APPROXIMATION FOR HIGH THROUGHPUTS LLMS

- README.md
> 🔥[DynamicKV] DynamicKV: Task-Aware Adaptive KV Cache Compression for Long Context LLMs

- README.md
🔥🔥[SP: TokenRing] TokenRing: An Efficient Parallelism Framework for Infinite-Context LLMs via Bidirectional Communication
> 🔥🔥[SP: TokenRing] TokenRing: An Efficient Parallelism Framework for Infinite-Context LLMs via Bidirectional Communication

- README.md
🔥🔥[FFPA] FFPA: Yet another Faster Flash Prefill Attention with O(1) SRAM complexity for headdim > 256, ~1.5x faster than SDPA EA(@DefTruth)
> 🔥🔥[FFPA] FFPA: Yet another Faster Flash Prefill Attention with O(1) SRAM complexity for headdim > 256, ~1.5x faster than SDPA EA(@DefTruth)

- README.md
…put-optimized Large Language Model Serving
> 🔥🔥[DistServe] DistServe: Disaggregating Prefill and Decoding for Goodput-optimized Large Language Model Serving

- README.md
> 🔥🔥[Mooncake] Mooncake: A KVCache-centric Disaggregated Architecture for LLM Serving

- README.md
🔥[DeepSeek-NSA] Native Sparse Attention: Hardware-Aligned and Natively Trainable Sparse Attention
> 🔥[DeepSeek-NSA] Native Sparse Attention: Hardware-Aligned and Natively Trainable Sparse Attention

- README.md
🔥[MHA2MLA] Towards Economical Inference: Enabling DeepSeek’s Multi-Head Latent Attention in Any Transformer-based LLMs
> 🔥[MHA2MLA] Towards Economical Inference: Enabling DeepSeek’s Multi-Head Latent Attention in Any Transformer-based LLMs

- README.md
> 🔥[X-EcoMLA] Upcycling Pre-Trained Attention into MLA for Efficient and Extreme KV Compression
